In [1]:
import numpy as np

## Cómo realizar copias de arreglos numpy?

In [2]:
arreglo = np.array(range(10))

In [3]:
arreglo

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# Copiar arreglo
arreglo2 = arreglo

In [5]:
arreglo2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arreglo[0] = 100
arreglo

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [7]:
arreglo2

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [8]:
arreglo_original = np.array([1, 2, 3])
arreglo_copia = arreglo_original.copy()
arreglo_original[0] = 200

In [9]:
print(arreglo_original)
print(arreglo_copia)

[200   2   3]
[1 2 3]
