In [1]:
import numpy as np

In [2]:
import math

In [3]:
math.sin(0)

0.0

In [7]:
# ndarray - n-dimensional

arreglo = np.array(range(10))

In [8]:
type(arreglo)

numpy.ndarray

In [9]:
dir(arreglo)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [10]:
arreglo.size

10

In [11]:
arreglo.shape

(10,)

In [12]:
arreglo.dtype

dtype('int64')

In [15]:
lista = [1, 1.1, True, ""]

In [16]:
np.array(lista)

array(['1', '1.1', 'True', ''], dtype='<U32')

In [17]:
matriz_python = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [18]:
type(matriz_python)

list

In [22]:
matriz_python[0][0]

1

In [23]:
matriz_numpy = np.array(matriz_python)

In [24]:
type(matriz_numpy)

numpy.ndarray

In [25]:
matriz_numpy.dtype

dtype('int64')

In [26]:
matriz_numpy.shape

(3, 3)

In [27]:
matriz_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# Matrices son Fi-Co
matriz_numpy[0, 0].item()

1

In [32]:
type(matriz_numpy[0, 0].item())

int

In [37]:
np.random.random()

0.8116468834735167

In [51]:
np.random.randint(101, size=(10,10))

array([[ 4, 60, 26,  0, 64, 48, 30, 96, 44, 66],
       [39, 32, 14, 54, 54, 50, 48, 64, 95, 61],
       [72, 50, 76, 57, 28,  9, 79,  5, 41, 83],
       [98, 40, 60, 16, 41, 70, 23, 98, 67,  5],
       [71, 45, 15, 12, 85, 82, 29, 54, 33, 55],
       [94,  6,  2, 79, 50,  6, 71, 10, 32, 20],
       [65, 36, 34,  1,  0, 82, 42, 34, 68, 82],
       [86, 37, 53, 71,  1, 11, 37, 62, 89, 74],
       [63, 38, 95, 44, 67, 38, 37, 96, 44,  5],
       [81, 56, 18, 75, 43,  7, 38,  5, 15, 34]])

In [52]:
np.random.seed(96)

In [53]:
np.random.randint(101, size=(10,10))

array([[ 84,  90,  38,  97,  97,  66,  54,  61,   6,  73],
       [ 62,   2,  90,  81,  61,   3,  60,  33,  97,  26],
       [ 79,  58,  24,  20,  61,  21,  76,   8,  65,  14],
       [ 10,  58,  20,  23,   8,  85,  21,   6,  84,  18],
       [ 89,  69,  67, 100,  95,  79,  61,  50,  57,  56],
       [ 35,  46,   7,  37,  38,  56, 100,  29,  75,  25],
       [ 90,  95,  34,  95,  45,  45,  24,  83,  25,  39],
       [ 66,  69,  44,  61,  61,  55,  65,   4,  18,  98],
       [ 78,  29,  82,  11,  74,  19,  77,  73,  60,  55],
       [ 80,   1,  58,  94,  60,  76,  64,  89,  20,   8]])

In [54]:
np.random.randint(101, size=(10,10))

array([[ 88,  12,   0,  42,   9,  18,  22,  46,  40,  39],
       [ 88,  87,  47,  50,  47,   7,  16,  59,  73,  41],
       [ 17,  70,  91,  21,  77,  43,  25,  21,  72,  24],
       [ 40,  99,  54,  78,  68,  91,   1,  46,  30,  50],
       [ 67,  68,   9, 100,  22,  98,  81,   2,  80,  17],
       [ 84,  67,  41,  96,  92,  37,  43,  91,  13,  69],
       [ 21,  72,  60,  21,  49,  41,  62,  85,   3,  61],
       [ 88,  84,  24,  21,  93,  84,  40,  65,  55,  89],
       [ 13,  46,  24,  17,  28,  68,  28,  20,  56,   4],
       [ 95,  34,  53,  20,  55,  93,  41,  60,  93,  21]])

In [55]:
matriz_10x10 = np.random.randint(101, size=(10,10))

In [56]:
matriz_10x10.size

100

In [57]:
matriz_10x10.shape

(10, 10)

In [58]:
matriz_10x10

array([[ 27,  12,  51,  34,  75,   3,  45,  88,  13,  35],
       [ 26,  12,  27,  92,  89,  75,  48,  68,  76,  65],
       [ 91,  28,  41,  47,  24,  14,  33,  75,  27,  24],
       [ 27,  33,  35,  29,  16,  81,  15,  69,  39,  72],
       [ 25,  32,  56,  88,  18,  56,  18,  63,  87,  17],
       [ 24,  70,  96, 100,  62,  94,  48,  64,  91,  57],
       [ 15,  63,  32,  30,   3,  37,  52,  61,  74,  38],
       [ 43,  18,  68,  95,  13,  54,  47,  33,  15,  78],
       [ 85,   9,  59,  55,  73,  57,   5,  46,  24,  86],
       [ 39,  67,   9,  62,  40,   9,  54,  58, 100,  57]])

In [59]:
matriz_10x10[2, 2]

np.int64(41)

In [60]:
matriz_10x10[8:]

array([[ 85,   9,  59,  55,  73,  57,   5,  46,  24,  86],
       [ 39,  67,   9,  62,  40,   9,  54,  58, 100,  57]])

In [62]:
matriz_10x10[8:, 3:6]

array([[55, 73, 57],
       [62, 40,  9]])

In [64]:
matriz_5x5 = np.random.randint(21, size=(5,5))

In [65]:
matriz_5x5

array([[11, 14,  8, 10,  2],
       [ 0,  6,  3, 18, 20],
       [ 9,  9, 20,  2, 12],
       [13, 17, 16,  6,  8],
       [17, 15, 14, 17,  0]])

In [66]:
matriz_5x5 + 5

array([[16, 19, 13, 15,  7],
       [ 5, 11,  8, 23, 25],
       [14, 14, 25,  7, 17],
       [18, 22, 21, 11, 13],
       [22, 20, 19, 22,  5]])

In [67]:
matriz_5x5 + matriz_5x5

array([[22, 28, 16, 20,  4],
       [ 0, 12,  6, 36, 40],
       [18, 18, 40,  4, 24],
       [26, 34, 32, 12, 16],
       [34, 30, 28, 34,  0]])

In [70]:
# matriz_5x5 // matriz_5x5

In [72]:
matriz_5x5

array([[11, 14,  8, 10,  2],
       [ 0,  6,  3, 18, 20],
       [ 9,  9, 20,  2, 12],
       [13, 17, 16,  6,  8],
       [17, 15, 14, 17,  0]])

In [ ]:
matriz_5x5 * matriz_5x5 # element-wise

array([[121, 196,  64, 100,   4],
       [  0,  36,   9, 324, 400],
       [ 81,  81, 400,   4, 144],
       [169, 289, 256,  36,  64],
       [289, 225, 196, 289,   0]])

In [73]:
matriz_5x5 @ matriz_5x5 # multiplicación matricial

array([[357, 510, 478, 472, 478],
       [601, 669, 646, 562, 300],
       [509, 574, 699, 508, 454],
       [501, 650, 683, 640, 606],
       [534, 743, 733, 570, 638]])

In [74]:
np.sin(matriz_5x5)

array([[-0.99999021,  0.99060736,  0.98935825, -0.54402111,  0.90929743],
       [ 0.        , -0.2794155 ,  0.14112001, -0.75098725,  0.91294525],
       [ 0.41211849,  0.41211849,  0.91294525,  0.90929743, -0.53657292],
       [ 0.42016704, -0.96139749, -0.28790332, -0.2794155 ,  0.98935825],
       [-0.96139749,  0.65028784,  0.99060736, -0.96139749,  0.        ]])

In [75]:
np.tanh(matriz_5x5)

array([[1.        , 1.        , 0.99999977, 1.        , 0.96402758],
       [0.        , 0.99998771, 0.99505475, 1.        , 1.        ],
       [0.99999997, 0.99999997, 1.        , 0.96402758, 1.        ],
       [1.        , 1.        , 1.        , 0.99998771, 0.99999977],
       [1.        , 1.        , 1.        , 1.        , 0.        ]])

In [76]:
np.sqrt(matriz_5x5)

array([[3.31662479, 3.74165739, 2.82842712, 3.16227766, 1.41421356],
       [0.        , 2.44948974, 1.73205081, 4.24264069, 4.47213595],
       [3.        , 3.        , 4.47213595, 1.41421356, 3.46410162],
       [3.60555128, 4.12310563, 4.        , 2.44948974, 2.82842712],
       [4.12310563, 3.87298335, 3.74165739, 4.12310563, 0.        ]])

In [77]:
matriz_5x5 ** 3

array([[1331, 2744,  512, 1000,    8],
       [   0,  216,   27, 5832, 8000],
       [ 729,  729, 8000,    8, 1728],
       [2197, 4913, 4096,  216,  512],
       [4913, 3375, 2744, 4913,    0]])

In [78]:
np.power(matriz_5x5, 3)

array([[1331, 2744,  512, 1000,    8],
       [   0,  216,   27, 5832, 8000],
       [ 729,  729, 8000,    8, 1728],
       [2197, 4913, 4096,  216,  512],
       [4913, 3375, 2744, 4913,    0]])